// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPj37Eq4Qqvrjbcgy1GmjP_BxxuQdo9LY',
    appId: '1:57263548130:web:f11639a95fa6072ca7a0bb',
    messagingSenderId: '57263548130',
    projectId: 'travelmate-434eb',
    authDomain: 'travelmate-434eb.firebaseapp.com',
    storageBucket: 'travelmate-434eb.appspot.com',
    measurementId: 'G-P9EMVE1NHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC56gXm7B4bx8bxTwP_IGOOC6jAA8bHh_8',
    appId: '1:57263548130:android:857aad0987f005cca7a0bb',
    messagingSenderId: '57263548130',
    projectId: 'travelmate-434eb',
    storageBucket: 'travelmate-434eb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPj37Eq4Qqvrjbcgy1GmjP_BxxuQdo9LY',
    appId: '1:57263548130:web:8dbcd73a7e5e758ca7a0bb',
    messagingSenderId: '57263548130',
    projectId: 'travelmate-434eb',
    authDomain: 'travelmate-434eb.firebaseapp.com',
    storageBucket: 'travelmate-434eb.appspot.com',
    measurementId: 'G-00T4EFLYN2',
  );
}
